export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Works } from "./Works";
export { default as Clients } from "./Clients";
export { default as Services } from "./Services";
export { default as OurTeam } from "./OurTeam";
export { default as Blog } from "./Blog";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
